// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	projectCreate: (path: string, name: string) => typedError<ProjectSnapshot, IpcError>(__TAURI_INVOKE("project_create", { path, name })),
	projectOpen: (path: string) => typedError<ProjectSnapshot, IpcError>(__TAURI_INVOKE("project_open", { path })),
	projectSaveAs: (path: string) => typedError<ProjectSnapshot, IpcError>(__TAURI_INVOKE("project_save_as", { path })),
	projectApplyEdit: (cmd: EditCommand) => typedError<EditOutcome, IpcError>(__TAURI_INVOKE("project_apply_edit", { cmd })),
	projectUndo: () => typedError<UndoOutcome, IpcError>(__TAURI_INVOKE("project_undo")),
	projectRedo: () => typedError<UndoOutcome, IpcError>(__TAURI_INVOKE("project_redo")),
	assetImport: (paths: string[]) => typedError<AssetId[], IpcError>(__TAURI_INVOKE("asset_import", { paths })),
	assetGet: (assetId: string) => typedError<AssetInfo, IpcError>(__TAURI_INVOKE("asset_get", { assetId })),
	assetPeaks: (assetId: string, zoomLevel: number) => typedError<PeakView, IpcError>(__TAURI_INVOKE("asset_peaks", { assetId, zoomLevel })),
	generateSubmit: (clipId: string, recipe: GenerationRecipe, priority: number | null) => typedError<string, IpcError>(__TAURI_INVOKE("generate_submit", { clipId, recipe, priority })),
	jobCancel: (jobId: string) => typedError<CancelOutcome, IpcError>(__TAURI_INVOKE("job_cancel", { jobId })),
	takeList: (clipId: string) => typedError<TakeInfo[], IpcError>(__TAURI_INVOKE("take_list", { clipId })),
	takePromote: (clipId: string, takeId: string) => typedError<EditOutcome, IpcError>(__TAURI_INVOKE("take_promote", { clipId, takeId })),
	takeStar: (takeId: string, starred: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("take_star", { takeId, starred })),
	takeDelete: (takeId: string) => typedError<null, IpcError>(__TAURI_INVOKE("take_delete", { takeId })),
	transportPlay: () => typedError<null, IpcError>(__TAURI_INVOKE("transport_play")),
	transportPause: () => typedError<null, IpcError>(__TAURI_INVOKE("transport_pause")),
	transportSeek: (positionMs: number) => typedError<null, IpcError>(__TAURI_INVOKE("transport_seek", { positionMs })),
	transportLoop: (startMs: number, endMs: number, enabled: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("transport_loop", { startMs, endMs, enabled })),
	transportPosition: () => typedError<TransportPosition, IpcError>(__TAURI_INVOKE("transport_position")),
	engineStatus: () => typedError<EngineStatus, IpcError>(__TAURI_INVOKE("engine_status")),
	engineSwitchBackend: (providerId: string) => typedError<null, IpcError>(__TAURI_INVOKE("engine_switch_backend", { providerId })),
	exportRender: (spec: ExportSpec) => typedError<string, IpcError>(__TAURI_INVOKE("export_render", { spec })),
};

/** Events */
export const events = {
	jobProgress: makeEvent<JobProgressEvent>("job:progress"),
	jobState: makeEvent<JobStateEvent>("job:state"),
	peaksReady: makeEvent<PeaksReadyEvent>("peaks:ready"),
	projectDirty: makeEvent<ProjectDirtyEvent>("project:dirty"),
	takeReady: makeEvent<TakeReadyEvent>("take:ready"),
};

/* Types */
export type Arrangement = {
	tracks: Track[],
};

/**
 *  Định danh asset theo nội dung (content-addressed): blake3 hex của file.
 *  Cùng nội dung → cùng id → dedupe tự nhiên trong store.
 */
export type AssetId = string;

/**  Metadata asset cho UI (đặt clip import theo độ dài thật). */
export type AssetInfo = {
	id: string,
	kind: string,
	duration_ms: number | null,
	sample_rate: number | null,
	channels: number | null,
};

/**  Ba kết cục cancel — KHÔNG được giả vờ huỷ thành công (AGENTS.md §6). */
export type CancelOutcome = "cancelled" | 
/**  Job đã dispatch xuống worker, không huỷ được nữa. UI phải nói rõ điều này. */
"too_late";

/**  Những gì provider làm được. */
export type Capability = "text2_music" | "cover" | "repaint" | "lego" | "extract" | "complete" | "understand" | "hot_swap_model" | "cancel_running_job" | "lora_training" | 
/**
 *  Provider tách được pha LM (plan) và pha DiT (render) thành 2 lời gọi.
 *  cpp có (`/lm` + `/synth`); py KHÔNG — release_task là single-shot,
 *  dù nó chấp nhận `audio_code_string` để bỏ qua LM ở lần sau.
 */
"split_plan_render";

export type Clip = {
	id: ClipId,
	/**  specta: u64 bị cấm export — ms luôn < 2^53 nên `number` là đủ. */
	start_ms: number,
	duration_ms: number,
	/**  Offset vào audio nguồn (trim đầu). */
	offset_ms: number,
	/**  specta: f32 render "number | null" — ép `number` (dB luôn hữu hạn). */
	gain_db: number,
	fade_in_ms: number,
	fade_out_ms: number,
	source: ClipSource,
	generation: GenerationInfo | null,
	/**  Take đang phát. None = chưa generate hoặc take cuối bị xoá. */
	active_take: TakeId | null,
};

/**  Định danh một clip trên timeline. */
export type ClipId = string;

export type ClipSource = { type: "imported"; asset: AssetId } | 
/**  Clip sinh bởi engine — audio thật nằm ở take active, không ở đây. */
{ type: "generated" };

/**  Lệnh chỉnh sửa từ UI. Mỗi lệnh phải undo được — kể cả thao tác async (plan §5). */
export type EditCommand = { op: "add_track"; kind: TrackKind; name: string } | { op: "remove_track"; track_id: TrackId } | 
/**
 *  clip_id do CLIENT sinh (uuid) — generate_submit cần tham chiếu clip
 *  ngay, không chờ vòng IPC quay lại.
 */
{ op: "add_clip"; track_id: TrackId; clip_id: ClipId; start_ms: number; duration_ms: number; source: ClipSource } | { op: "move_clip"; clip_id: ClipId; to_track: TrackId; start_ms: number } | { op: "trim_clip"; clip_id: ClipId; start_ms: number; duration_ms: number; offset_ms: number } | { op: "split_clip"; clip_id: ClipId; at_ms: number } | { op: "set_track_gain"; track_id: TrackId; gain_db: number } | { op: "set_track_pan"; track_id: TrackId; pan: number } | { op: "set_track_mute"; track_id: TrackId; mute: boolean } | { op: "set_track_solo"; track_id: TrackId; solo: boolean } | { op: "set_active_take"; clip_id: ClipId; take_id: TakeId } | { op: "remove_clip"; clip_id: ClipId };

export type EditOutcome = {
	edit: EditResult,
	snapshot: ProjectSnapshot,
};

export type EditResult = {
	/**  Nhãn hiển thị trong menu Undo, vd "Move clip". */
	label: string,
};

/**  Payload của `engine_status` và event `engine:status`. */
export type EngineStatus = {
	backend: ProviderId,
	ready: boolean,
	warm_models: string[],
	/**  specta: u64 bị cấm export — MB luôn < 2^53. */
	vram_free_mb: number | null,
	queue_depth: number,
	/**
	 *  Provider active LÀM ĐƯỢC gì — UI ẩn/hiện theo đây, CẤM hardcode
	 *  trong component (issue #10 / ALS-F05, AGENTS §7).
	 */
	capabilities: Capability[],
	/**  Model provider nhận diện được — dropdown model đọc từ đây. */
	models: ModelDescriptor[],
};

export type ErrorCode = "PROJECT_NOT_FOUND" | "PROJECT_CORRUPT" | 
/**  Project được tạo bởi app version mới hơn — từ chối mở, yêu cầu cập nhật. */
"SCHEMA_TOO_NEW" | "ASSET_NOT_FOUND" | 
/**  Xoá asset khi vẫn còn take/clip tham chiếu. */
"ASSET_IN_USE" | "PROVIDER_UNAVAILABLE" | 
/**  Provider hiện tại không có capability mà task yêu cầu (vd cpp không có repaint). */
"CAPABILITY_NOT_SUPPORTED" | "JOB_NOT_FOUND" | 
/**  Huỷ job khi đã dispatch xuống worker — xem ADR-001 mục Hệ quả. */
"JOB_TOO_LATE" | "MODEL_MISSING" | "VRAM_EXHAUSTED" | "INVALID_RECIPE" | "EXPORT_FAILED" | "IO" | "INTERNAL";

export type ExportFormat = 
/**  Master WAV 48kHz 24-bit. */
"wav24" | "mp3" | "flac";

export type ExportRange = { type: "project" } | { type: "loop"; start_ms: number; end_ms: number };

export type ExportSpec = {
	format: ExportFormat,
	range: ExportRange,
	out_path: string,
	/**  Nhúng metadata recipe + disclosure "AI-generated" (plan §S6). */
	include_metadata: boolean,
};

/**  Lineage của clip generate: recipe đầy đủ để tái lập (plan §5). */
export type GenerationInfo = {
	recipe: GenerationRecipe,
};

export type GenerationRecipe = {
	/**  Caption / style tags. Chuỗi rỗng + lyrics rỗng = engine tự sinh cả hai. */
	prompt: string,
	/**  `""` = LM tự sinh lời; `"[Instrumental]"` = không vocal (chuỗi engine đã train). */
	lyrics: string,
	/**  10..=600 giây. */
	duration_s: number,
	/**  30..=300 */
	bpm: number | null,
	key_scale: string | null,
	/**  Chỉ nhận 2 | 3 | 4 | 6. */
	time_signature: number | null,
	/**  Mã ngôn ngữ vocal, vd `"vi"`, `"en"`. None = để LM tự suy. */
	vocal_language: string | null,
	task: TaskType,
	model_tier: ModelTier,
	/**  Audio tham chiếu phong cách (cover/complete). */
	reference_audio: AssetId | null,
	/**  Audio nguồn (repaint/cover/extract/lego). */
	source_audio: AssetId | null,
	/**
	 *  (start_ms, end_ms) — bắt buộc khi task = repaint.
	 *  specta: u64 bị cấm export — ms luôn < 2^53 nên `number` là đủ.
	 */
	repaint_range_ms: [number, number] | null,
	sampling: SamplingParams,
	provider_overrides?: ProviderOverrides,
};

export type InferMethod = "ode" | "sde";

export type IpcError = {
	code: ErrorCode,
	message: string,
	retryable: boolean,
};

/**  Định danh một job trong queue của orchestrator. */
export type JobId = string;

export type JobProgressEvent = {
	job_id: JobId,
	/**  0..=100 */
	percent: number,
	stage: ProgressStage,
};

export type JobState = "queued" | "dispatching" | "running" | "postprocess" | "done" | "failed" | "cancelled";

export type JobStateEvent = {
	job_id: JobId,
	state: JobState,
	error: string | null,
};

/**  Một model provider nhận diện được (đã cài / biết đường tải). */
export type ModelDescriptor = {
	id: ModelId,
	tier: ModelTier,
	/**
	 *  Checksum file trọng số (blake3 hex). Đi vào render_hash — đổi quant
	 *  (Q8_0 → Q4_K_M) đổi checksum → không trả nhầm cache cũ.
	 */
	checksum: string,
	/**  specta: u64 bị cấm export — MB luôn < 2^53. */
	vram_estimate_mb: number | null,
	warm: boolean,
};

/**
 *  Định danh model cụ thể phía provider (vd `acestep-v15-turbo`,
 *  `acestep-v15-turbo-Q8_0.gguf`). Không trùng với [`crate::ModelTier`] —
 *  tier là trừu tượng, id là hiện thực.
 */
export type ModelId = string;

/**
 *  Tier model trừu tượng. Mỗi provider map tier → model id cụ thể
 *  (vd `turbo` → `acestep-v15-turbo` hoặc `acestep-v15-turbo-Q8_0.gguf`).
 */
export type ModelTier = "turbo" | "sft" | "base" | "xl_turbo" | "xl_sft" | "xl_base";

export type PeakView = {
	spp: number,
	/**
	 *  specta: f32 render "number | null" — ép `[number, number][]`
	 *  (min/max peak luôn hữu hạn trong [-1, 1]).
	 */
	pairs: ([number, number])[],
};

export type PeaksReadyEvent = {
	asset_id: AssetId,
};

export type ProgressStage = "queued" | "planning" | "rendering" | "postprocess";

export type ProjectDirtyEvent = {
	dirty: boolean,
};

/**  Định danh một project. */
export type ProjectId = string;

/**  Snapshot gửi qua IPC khi open/create project. */
export type ProjectSnapshot = {
	project_id: ProjectId,
	name: string,
	schema_version: number,
	arrangement: Arrangement,
	dirty: boolean,
};

/**
 *  Định danh provider — chuỗi ổn định, KHÔNG phải uuid.
 *  Nằm trong render_hash/plan_hash nên đổi chuỗi này = vô hiệu toàn bộ cache.
 */
export type ProviderId = string;

/**
 *  Tham số riêng của provider/engine. Không tham gia plan_hash,
 *  CÓ tham gia render_hash. `extra` là BTreeMap — luôn duyệt theo thứ tự sort.
 */
export type ProviderOverrides = {
	/**  `vllm` | `pt` — chỉ có nghĩa với provider py. */
	lm_backend: string | null,
	/**
	 *  specta: serde_json::Value liệt kê i64/u64 nội bộ bị cấm export —
	 *  UI chỉ đọc qua, export thành `Record<string, unknown>`.
	 */
	extra?: { [key in string]: unknown },
	lm_model: string | null,
};

/**  Tham số sampling — CHỈ nhóm này tham gia render_hash, không tham gia plan_hash. */
export type SamplingParams = {
	/**
	 *  None = engine tự random (`use_random_seed=true` phía ACE-Step).
	 *  specta: u64 bị cấm export — seed chỉ hiển thị ở UI, `number` đủ
	 *  (giá trị > 2^53 sẽ hiển thị xấp xỉ; engine vẫn nhận đủ 64 bit).
	 */
	seed: number | null,
	inference_steps: number,
	/**  Chỉ có tác dụng trên tier base. UI phải ẩn khi model là turbo. */
	guidance_scale: number | null,
	/**  Chỉ có tác dụng trên tier base. */
	shift: number | null,
	infer_method: InferMethod,
	/**  1..=8 */
	batch_size: number,
};

/**  Định danh một take (một lần render) của clip. */
export type TakeId = string;

/**
 *  Thông tin một take trả về UI (take rack). Tách khỏi TakeRow nội bộ của
 *  als-project: IPC chỉ thấy kiểu này.
 */
export type TakeInfo = {
	id: TakeId,
	clip_id: string,
	plan_hash: string,
	render_hash: string,
	asset_id: AssetId,
	/**  Integrated loudness (LUFS), None khi postprocess đo lỗi. */
	lufs: number | null,
	true_peak_db: number | null,
	starred: boolean,
	/**  specta: i64 bị cấm export — unix giây fit i32 tới 2038. */
	created_at_unix: number,
};

export type TakeReadyEvent = {
	job_id: JobId,
	clip_id: string,
	take_id: TakeId,
	/**  true = cache tầng 2 trúng — take đã tồn tại, UI gắn bằng SetActiveTake. */
	cached: boolean,
};

/**  Task của ACE-Step. Serialize khớp đúng chuỗi `task_type` của engine. */
export type TaskType = "text2music" | "cover" | "repaint" | "lego" | "extract" | "complete";

export type Track = {
	id: TrackId,
	kind: TrackKind,
	name: string,
	/**  specta: f32 render "number | null" — ép `number`. */
	gain_db: number,
	/**  -1.0 (trái) ..= 1.0 (phải) */
	pan: number,
	mute: boolean,
	solo: boolean,
	clips: Clip[],
};

/**  Định danh một track. */
export type TrackId = string;

export type TrackKind = 
/**  Audio import từ ngoài. */
"audio" | 
/**  Track chứa clip do engine sinh ra. */
"generated";

export type TransportPosition = {
	/**  specta: u64 bị cấm export — playhead < 2^53 frame trong mọi session. */
	frames: number,
	playing: boolean,
};

export type UndoOutcome = {
	label: string | null,
	snapshot: ProjectSnapshot | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

