[package]
name = "als-provider-cpp"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
als-core.workspace = true
als-provider.workspace = true
async-trait.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
