[package]
name = "als-media"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
thiserror.workspace = true
symphonia.workspace = true
rubato.workspace = true
ebur128.workspace = true
tracing.workspace = true

[dev-dependencies]
hound.workspace = true
tempfile.workspace = true
